project:
  type: website
  output-dir: docs

website:
  title: "omiridoue"
  description: "Eleni Omiridou's personal website"
  favicon: "images/logo_sgsss.png"
  google-analytics: "G-43L15MR1WY"
  twitter-card:
    creator: "@omiridoue"
  site-url: https://omiridoue.github.io
  repo-url: https://github.com/omiridoue.github.io
  repo-actions: [edit, issue]
  navbar:
    title: false
    logo: "images/logo_sgsss.png"
    background: primary
    search: true
    left: 
      - text: "{{< fa house-user >}} Home"
        href: index.qmd
      - text: "{{< fa diagram-project >}} Projects"
        href: projects.qmd
      - text: "{{< fa address-card >}} About"
        href: about.qmd
      - text: "{{< fa paper-plane >}} Contact"
        href: mailto:e.omiridou.1@research.gla.ac.uk
    right:
      - icon: github
        href: https://github.com/omiridoue
  page-footer:
    background: primary
    left: "{{< fa copyright >}} 2024, Eleni Omiridou, powered by <a href='https://quarto.org/docs/publishing/github-pages.html'>Quarto</a>, a fork of <a href='https://github.com/robertmitchellv/robertmitchellv.github.io'>robertvmitchell </a>"    
    center:
      - text: "<img src='/images/MRC_CSO_SPHSU_Glasgow_RGB_0.png' width='auto' height='50px'>"
    right:
      - icon: github
        href: https://github.com/omiridoue

format:
  html:
    theme:
      light: [flatly, custom.scss]
      dark: [darkly, custom-dark.scss]
